cmake_minimum_required(VERSION 3.10)
project(heartrate)

SET(CMAKE_CXX_FLAGS_DEBUG "-O0")
SET(CMAKE_C_FLAGS_DEBUG "-O0")

add_subdirectory(utils/bandpass_filter)
add_subdirectory(utils/adaptive_filter)
add_subdirectory(utils/adaptive_filter_float)
add_subdirectory(utils/kalman_filter)
add_subdirectory(utils/kalman_filter_float)
add_subdirectory(utils/fft_library)
add_subdirectory(utils/fft_library_float)
add_subdirectory(utils/rolling_stats)
add_subdirectory(utils/rolling_stats_float)
add_subdirectory(algorithms/dummy)
add_subdirectory(algorithms/espruino)
add_subdirectory(algorithms/fft) 
add_subdirectory(algorithms/autocorrelation) 
add_subdirectory(algorithms/oxford)
add_subdirectory(algorithms/pantompkins)
add_subdirectory(algorithms/autocorrelation2) 
add_subdirectory(algorithms/algo1)
add_subdirectory(algorithms/fft2)
add_subdirectory(algorithms/spectralTracking)
add_subdirectory(algorithms/final)
add_subdirectory(algorithms/finalShort)
add_subdirectory(algorithms/debug1)
add_subdirectory(algorithms/debug2)
add_subdirectory(algorithms/debug3)
add_subdirectory(algorithms/debug4)
add_subdirectory(algorithms/debug5)
add_subdirectory(algorithms/debug6)
add_subdirectory(algorithms/debug7)
add_subdirectory(algorithms/debug9)
add_subdirectory(algorithms/debug10)
add_subdirectory(algorithms/debug11)
add_subdirectory(algorithms/TRUST_PPG1)
add_subdirectory(algorithms/TRUST_PPG1_emp)
add_subdirectory(algorithms/TRUST_PPG2)
add_subdirectory(algorithms/TRUST_PPG2_emp)
add_subdirectory(algorithms/TRUST_PPG3)
add_subdirectory(algorithms/TRUST_PPG3_emp)
add_subdirectory(algorithms/TRUST_PPG4)
add_subdirectory(algorithms/TRUST_PPG4_emp)



add_executable(heartrate main.c)

target_link_libraries(heartrate bandpass_filter)
target_link_libraries(heartrate adaptive_filter)
target_link_libraries(heartrate adaptive_filter_float)
target_link_libraries(heartrate kalman_filter)
target_link_libraries(heartrate kalman_filter_float)
target_link_libraries(heartrate fft_library)
target_link_libraries(heartrate fft_library_float)
target_link_libraries(heartrate rolling_stats)
target_link_libraries(heartrate rolling_stats_float)
target_link_libraries(heartrate dummy)
target_link_libraries(heartrate espruino)
target_link_libraries(heartrate fft)
target_link_libraries(heartrate autocorrelation)
target_link_libraries(heartrate oxford)
target_link_libraries(heartrate pantompkins)
target_link_libraries(heartrate autocorrelation2)
target_link_libraries(heartrate algo1)
target_link_libraries(heartrate fft2)
target_link_libraries(heartrate spectralTracking)
target_link_libraries(heartrate final)
target_link_libraries(heartrate finalShort)
target_link_libraries(heartrate debug1)
target_link_libraries(heartrate debug2)
target_link_libraries(heartrate debug3)
target_link_libraries(heartrate debug4)
target_link_libraries(heartrate debug5)
target_link_libraries(heartrate debug6)
target_link_libraries(heartrate debug7)
target_link_libraries(heartrate debug9)
target_link_libraries(heartrate debug10)
target_link_libraries(heartrate debug11)
target_link_libraries(heartrate TRUST_PPG1)
target_link_libraries(heartrate TRUST_PPG1_emp)
target_link_libraries(heartrate TRUST_PPG2)
target_link_libraries(heartrate TRUST_PPG2_emp)
target_link_libraries(heartrate TRUST_PPG3)
target_link_libraries(heartrate TRUST_PPG3_emp)
target_link_libraries(heartrate TRUST_PPG4)
target_link_libraries(heartrate TRUST_PPG4_emp)

